theme: jekyll-theme-minimal

title: João Vitor de Paiva Marcotti

description: >
  I am currently working full-time as a Data Analyst at FIESC's economic observatory in Brazil, and as a Data Science Freelancer at Whiskystats, based in the Netherlands.<br><br>
  I hold bachelor's degrees in Economics (UniCesumar – Brazil) and Electrical Engineering (Universidade Estadual de Maringá – Brazil), as well as a postgraduate degree in Big Data from Fundação Getúlio Vargas (Brazil).<br><br>
  Driven by continuous learning, I am currently enrolled in a postgraduate program in Computer Vision at Data Science Academy (Brazil).

show_downloads: false
