theme: jekyll-theme-minimal

title: João Vitor de Paiva Marcotti

description: >

  Hi there 👋<br><br>
  
  I am João, born and raised in Brazil.<br><br>
  
  Data analyst at FIESC's Economic Observatory and data science freelancer at Whiskystats with a strong background in Electrical Engineering and Economics.<br><br>
  
  Skilled in Python, R, SQL and PySpark. Experienced in ETL pipelines, API development, big data analysis on Databricks, macroeconomic data validation, time series analysis and machine learning modeling.<br><br>
  
  Currently learning about computer vision.<br><br>
  
  As side hustle, I am currently working on:<br><br>
  - Whisky recommendation system.<br><br>
  - Casks valuation tool based on machine learning.<br><br>
  - Bottle filling level classifier based on computer vision.<br><br>
  
  How to reach me:<br><br>
  - Email: joaopaiva.datascience@gmail.com<br><br>
  - LinkedIn: https://www.linkedin.com/in/joao-vitor-de-paiva-marcotti

show_downloads: false
