theme: jekyll-theme-minimal

title: João Vitor de Paiva Marcotti

description: >
  <a href="index.html">Home</a> | 
  <a href="portfolio.html">Portfolio</a> | 
  <a href="academic_publications.html">Academic Publications</a>
  <br><br>

show_downloads: false
